---

version: '3'

x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "${LOGGING_MAX_SIZE}"
    max-file: "${LOGGING_MAX_FILE}"

x-network-internal:
  &network-internal
  - 'monitoring_node'

networks:
  monitoring_node: {}

services:
  cadvisor:
    image: 'google/cadvisor:v0.31.0'
    privileged: true
    logging: *default-logging
    networks: *network-internal
    user: 'root'
    command:
      - '/usr/bin/cadvisor'
      - '-port 8080'
      - '-logtostderr'
    volumes:
      - '/:/rootfs:ro'
      - '/cgroup/:/cgroup:ro'
      - '/dev/disk/:/dev/disk:ro'
      - '/dev/kmsg/:/dev/kmsg:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/var/run:/var/run:rw'
    restart: 'unless-stopped'
    expose:
      - 8080
    ports:
      - "${LISTEN_IP_ADDRESS}:8080:8080"

  node_exporter:
    image: 'bitnami/node-exporter:0.17.0'
    user: 'root'
    privileged: true
    logging: *default-logging
    networks: *network-internal
    volumes:
      - '/:/rootfs:ro'
      - '/cgroup/:/cgroup:ro'
      - '/dev/disk/:/dev/disk:ro'
      - '/proc:/host/proc:ro'
      - '/run:/run:ro'
      - '/sys:/host/sys:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.logind'
      - '--collector.mountstats'
      - '--collector.systemd'
      - '--collector.tcpstat'
    restart: 'unless-stopped'
    expose:
      - 9100
    ports:
      - "${LISTEN_IP_ADDRESS}:9100:9100"

  process_exporter:
    image: 'ncabatoff/process-exporter:0.4.0'
    privileged: true
    logging: *default-logging
    networks: *network-internal
    volumes:
      - '/proc:/host/proc:ro'
    command:
      - '-procfs=/host/proc'
      - "-procnames=${PROCESS_EXPORTER_PROCNAMES}"
    restart: 'unless-stopped'
    expose:
      - 9256
    ports:
      - "${LISTEN_IP_ADDRESS}:9256:9256"
