---

version: '3.4'

x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "${LOGGING_MAX_SIZE}"
    max-file: "${LOGGING_MAX_FILE}"

x-network-internal:
  &network-internal
  - 'monitoring_node'

networks:
  monitoring_node: {}

services:
  cadvisor:
    image: "${CADVISOR_IMAGE_NAME}:${CADVISOR_IMAGE_VERSION}"
    command:
      - '/usr/bin/cadvisor'
      - '-port 8080'
      - '-logtostderr'
    privileged: true
    restart: 'unless-stopped'
    user: 'root'
    logging: *default-logging
    networks: *network-internal
    expose:
      - 8080
    ports:
      - "${LISTEN_IP_ADDRESS}:8080:8080"
    volumes:
      - '/:/rootfs:ro'
      - '/cgroup/:/cgroup:ro'
      - '/dev/disk/:/dev/disk:ro'
      - '/dev/kmsg/:/dev/kmsg:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/var/run:/var/run:rw'

  node_exporter:
    image: "${NODE_EXPORTER_IMAGE_NAME}:${NODE_EXPORTER_IMAGE_VERSION}"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(dev|etc|host|proc|run|sys|var\/lib\/docker\/containers\/.*\/mounts\/shm)($$|/)'
      - '--collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|squashfs|sysfs|tracefs)$$'
      - '--collector.logind'
      - '--collector.mountstats'
      - '--collector.systemd'
      - '--collector.tcpstat'
      - '--collector.time'
      - '--collector.uname'
    privileged: true
    restart: 'unless-stopped'
    user: 'root'
    logging: *default-logging
    networks: *network-internal
    expose:
      - 9100
    ports:
      - "${LISTEN_IP_ADDRESS}:9100:9100"
    volumes:
      - '/:/rootfs:ro'
      - '/cgroup/:/cgroup:ro'
      - '/dev/disk/:/dev/disk:ro'
      - '/proc:/host/proc:ro'
      - '/run:/run:ro'
      - '/sys:/host/sys:ro'

  process_exporter:
    image: "${PROCESS_EXPORTER_IMAGE_NAME}:${PROCESS_EXPORTER_IMAGE_VERSION}"
    command:
      - '-procfs=/host/proc'
      - "-procnames=${PROCESS_EXPORTER_PROCNAMES}"
    privileged: true
    restart: 'unless-stopped'
    logging: *default-logging
    networks: *network-internal
    expose:
      - 9256
    ports:
      - "${LISTEN_IP_ADDRESS}:9256:9256"
    volumes:
      - '/proc:/host/proc:ro'
