---

version: '3'

networks:
  monitoring_node: {}

services:
  netdata:
    image: 'netdata/netdata:v1.11.1'
    user: 'root'
    privileged: true
    logging:
      driver: 'json-file'
      options:
        max-size: "${LOGGING_MAX_SIZE}"
        max-file: "${LOGGING_MAX_FILE}"
    volumes:
      - '/:/rootfs:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - './config/netdata/netdata.conf:/etc/netdata/netdata.conf'
    command:
      - '/usr/sbin/netdata'
      - '-D'
      - '-s /host'
      - '-p 19999'
    restart: 'unless-stopped'
    expose:
      - 19999
    ports:
      - "${LISTEN_IP_ADDRESS}:19999:19999"
    networks:
      - 'monitoring_node'
